name: dogo_ai_assistant
description: Un assistant de planification intelligent basÃ© sur l'IA et les habitudes.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.1.5
  shared_preferences: ^2.2.2
  http: ^1.5.0
  flutter_localizations:
    sdk: flutter
  flutter_local_notifications: ^14.0.0
  flutter_map: any
  latlong2: any
  geocoding: any
  timezone: any
  url_launcher: any
  geolocator: any
  permission_handler: ^10.4.0
  
  
  firebase_core: ^2.27.1
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.9
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/